### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by lorenzoznerol** [BMHLab/DiCER#12]
Dear Kevin,

congratulations for the tool! I'm using it with my own pre-processed data (ICA-AROMA+2P), but DiCER_lightweight.sh returns me with the following error after performing correctly FAST:

>> ./DiCER_lightweight.sh -i filtered_fmri.nii.gz -a structural.nii -w $subjects/BS_HC_01 -s BS_HC_01 -d

Unfolded 91x109x91x395 time-series matrix using Fortran ordering
Read in 902629x395 time series data
Unfolded 91x109x91x395 time-series matrix using Fortran ordering
Traceback (most recent call last):
  File "carpetCleaning/clusterCorrect.py", line 376, in <module>
    X = fMRI_in_out.timeSeriesData(ts_file,mask_file,maskIndex=maskLabel)
  File "/home/pnc/Desktop/Pipeline_imaging/scripts/DiCER/carpetCleaning/../utils/fMRI_in_out.py", line 55, in timeSeriesData
    X = Xraw[M==maskIndex,:]
IndexError: too many indices for array

- filtered_fmri: 4D preprocessed fMRI in MNI space
- structural: raw T1w

Do you have any idea where is the problem?
Lorenzo

**Comment by KevinAquino** [comment]
Hiya Lorenzo!

sorry for the delay, can you tell me the size of the anatomical image?

Also is the T1w in MNI space as well?

**Comment by Lorenzopinipsy** [comment]
I have done several attemps and this error returns also using T1 in MNI space 91x109x91 2mm (same space of rsfMRI preprocessed input)

The scripts create the files *detrended_hpf.nii.gz and *detrended_hpf_GMR.nii.gz but the same error returns several times within the terminal.

**Comment by KevinAquino** [comment]
Can i ask - which version of FSL are you using? also can you send me a screenshot of the folder? it looks like something has gone wrong with the mask! 

It might be a quirk of FSL's FAST, can you check out the output of BS_HC_01_dtissue_func.nii.gz? what is the size of that matrix and does the file look sensible - you should have a file with mask values of: 1,2,3,4

**Comment by Lorenzopinipsy** [comment]
I use FSL version 6.0. The mask dtissue_func.nii.gz is a 4D volume in MNI space (91x109x91 2mm) with n volumes = rsfMRI volumes. The first volume has values of 1,2,3,4. From 2:n, the mask has the same structure (and values) of my rsfMRI.
Attached the screenshot of the folder and the dtissue_func.nii.gz mask.
![DiCER_test](https://user-images.githubusercontent.com/35594736/84121433-77ea7a00-aa37-11ea-955f-413008ec5284.png)

**Comment by KevinAquino** [comment]
cool thanks for that! this is a problem that has only appeared with FSL6+ dtissue_func should only have 1 volume. Ill work on this, and send through the fix asap!

**Comment by Lorenzopinipsy** [comment]
Thanks for your help. I modified the code splitting the dtissue_func. The IndexError was solved, but now there is a MemoryError:

Perfoming DiCER..

Unfolded 91x109x91x395 time-series matrix using Fortran ordering
Read in 902629x395 time series data
Unfolded 91x109x91 mask matrix using Fortran ordering
Filtered to 95051x395 time series (in the mask)
No downsampling
Filtered to 95051 x 395 time series
Traceback (most recent call last):
  File "carpetCleaning/clusterCorrect.py", line 396, in <module>
    rowOrdering = clusterReorder.reorderMatrixRows(Xd)
  File "/home/pnc/Desktop/DiCER_prova_2/DiCER/carpetCleaning/../fmriprepProcess/clusterReorder.py", line 32, in reorderMatrixRows
    dij = distance.pdist(X,metric=distanceMetric)
  File "/usr/local/lib/python2.7/dist-packages/scipy/spatial/distance.py", line 1985, in pdist
    dm = np.empty((m * (m - 1)) // 2, dtype=np.double)
MemoryError

**Comment by KevinAquino** [comment]
awesome! i will add this to the code.

with the memory issues - this is because of the limits computationally  in the spatial domain. To speed this up, we have included options to have sparse sampling of hte time series, which we use if we have higher resolution data.

i would use the "p" flag -p 6 will do the trick.

**Comment by KevinAquino** [comment]
Also @Lorenzopinipsy I have updated the DiCER_lightweight.sh code can you pull this see if that works now? thanks! you can try -p 12 for a very sparse sampling to see if it works all the way through (it gives you a rough idea).

**Comment by Lorenzopinipsy** [comment]
Yes, now it works! I have only a last issue when running the carpet reports:

.Image Exception : #5 :: Out of Bounds (time index)
Out of Bounds (time index)
.Image Exception : #63 :: No image files match: /DiCER_test//tmp_dir/-FUNC1
Image Exception : #22 :: Failed to read volume /DiCER_test//tmp_dir/-FUNC1
Error : No image files match: /DiCER_test//tmp_dir/-FUNC1
terminate called after throwing an instance of 'armawrap::AWException'
  what():  Failed to read volume /DiCER_test//tmp_dir/-FUNC1
Error : No image files match: /DiCER_test//tmp_dir/-FUNC1
Aborted (core dumped)
Image Exception : #63 :: No image files match: /DiCER_test//tmp_dir/-Diff
Image Exception : #22 :: Failed to read volume /DiCER_test//tmp_dir/-Diff
Error : No image files match: /DiCER_test//tmp_dir/-Diff
Failed to read volume /DiCER_test//tmp_dir/-Diff
Error : No image files match: /DiCER_test//tmp_dir/-Diff

Within my tmp_dir folder I have the -FUNC0.nii.gz file and the -DiffSDhat.nii.gz, but FUNC1 and -Diff are missing

**Comment by KevinAquino** [comment]
Hmm this seems like something is going wrong - these commands are from AFNI to calculate DVARS. 

it is also strange that there is a reference to "/DiCER_test/" looks like its trying to look at a root directory.

What version of AFNI are you using?

**Comment by Lorenzopinipsy** [comment]
Version AFNI_19.3.13 'Nero'
Despite this error, the script creates carpet.png for GSO, RO and CO voxel ordering.

**Comment by KevinAquino** [comment]
awesome! sorry about the delay here I will have to see if it works for later versions of AFNI!

(might be an AFNI issue to calculate DVARS)

**Comment by KevinAquino** [comment]
I will go ahead and close this issue - this looks like a version issue, something that will be fixed up in an update soon!
